### ISSUE TITLE
Order doesn't seem to be working at the root level with files and directories mix

### ISSUE THREAD

**Issue by imolorhe** [ozum/vuepress-bar#36] opened 2021-05-23 14:34 UTC
I am using this plugin in a vuepress docs site with several directories and files at the root of the docs. I added `order` in the  frontmatter of the files and to the `README.md` files in the directories, but the sidebar order is still being done alphabetically.

**Comment by ozum** [comment] 2021-05-23 14:58
I couldn't find any info about `order` keyword in vuepress default theme. It seems that it is a custom behaviour described here: https://vuepress.vuejs.org/theme/writing-a-theme.html#site-and-page-metadata

I may be wrong. Could you please link docs where `order` for default theme is described?

**Comment by imolorhe** [comment] 2021-05-23 15:12
No I meant `order` as it is used in `vuepress-bar` (from the frontmatter) https://github.com/ozum/vuepress-bar/blob/master/lib/index.js#L87. It only seems to work for nested files. It doesn't work for nested directories though (i.e. setting the order in the `README.md` of the directories doesn't change the order of the directory sidebar link)

**Comment by ozum** [comment] 2021-05-23 17:16
Ok, I see. To understand what's wrong, could you please create a simple repo showing the problem and what's the expected behavior. So, I can check and correct the problem if possible.

**Comment by ozum** [comment] 2021-08-28 04:53
I will close the issue because a long time has passed since the last activity.

**Closed as completed by ozum** 2021-08-28 04:53 UTC

**Comment by ssuess** [comment] 2021-09-27 05:53
I think i have the same issue as the person above. Giving a number to both directories and documents in the same folder does not order them as one would expect. Only the documents are ordered, and the directories fall after that. Here is my tree for example:
```
├── 01.getting-started
│   ├── data-sources.md
│   ├── documentation.md
│   └── faq.md
├── 02.data-api
│   ├── 01.data-api.md
│   ├── assets
│   └── contact-finder.md
├── 03.the-ui
│   ├── 01.releases
│   │   ├── 202109241339.md
│   │   └── README.md
│   └── 02.ui-features.md
└── README.md
```
I would expect the folder `01.releases` to show in the list under `03.the-ui` first, before `02.ui-features`, but it does not. If I name a file instead of a folder there, it does properly sort.  So the issue is mixing files and directories with numbering. Thanks btw for this really great plugin!

**Comment by ssuess** [comment] 2021-09-27 06:08
and there seems to be a config setting that sets this by default to true (if I am understanding it correctly) but it does not work setting it to either true or false: `mixDirectoriesAndFilesAlphabetically`
