### ISSUE TITLE
Sidebar won't display

### ISSUE THREAD

**Issue by macguirerintoul** [ozum/vuepress-bar#4] opened 2019-07-26 22:45 UTC
Hi there,

First of all, thanks for creating this — but I can't get it to work with my Vuepress instance. Below is my `.vuepress/config.js`. My directory structure is as follows. I would like to have a different sidebar for `/en`, `/fr`, etc. as they will be in different languages. Can you spot what I'm doing wrong?

```
./
  |- .vuepress/
    |- config.js
  |- en/
    |- 01.about/
      |- introduction.md
      |- contributing.md
    |- 02.terms/
      |- example.md
      |- test.md
  |- fr/
    |- ...

```

```
const getConfig = require('vuepress-bar');
const config = getConfig('en');
console.log(config)

module.exports = {
  port: 3000,
  serviceWorker: true,
  ga: 'UA-144587327-1',
  themeConfig: {
    themeConfig: {
      nav: [
        { text: 'Home', link: '/' },
        {
          text: 'GitHub',
          link: 'https://github.com/mrintoul/DesignDictionary.xyz',
        },
        ...config.nav,
      ],
      sidebar: config.sidebar,
    },
    locales: {
      '/': {
        label: 'English',
      },
      '/fr/': {
        label: 'Français',
        selectText: 'Langues',
        nav: [
          { text: 'Accueil', link: '/fr/' },
          {
            text: 'GitHub',
            link: 'https://github.com/mrintoul/DesignDictionary.xyz',
          },
        ],
        // sidebar: getSidebar('./fr/'),
      },
    },
  },
  locales: {
    '/': {
      lang: 'en-US',
      title: 'DesignDictionary.xyz',
      description: 'The open-source dictionary for design',
    },
    '/fr/': {
      lang: 'fr',
      title: 'DesignDictionary.xyz',
      description: 'Le dictionnaire source-ouverte pour design',
    },
  },
};
```

**Comment by ozum** [comment] 2019-11-03 09:08
Sorry for late answer. Github didn't sent me notifications for this repo.

Could you please provide a sample repo, so I can examine the problem. Thanks.

**Comment by AGDholo** [comment] 2019-11-16 15:36
@ozum you need click "watch" button in the head of page to recive notification

**Comment by ozum** [comment] 2019-11-16 15:39
Ahh it was in `not watching` state for this repo, I don't know why. Changed that. Thanks.

**Comment by ozum** [comment] 2019-12-04 14:02
Since I could not reproduce the problem and no example repo provided for a long time, I'm closing the case. Please feel free to create another case with a sample repo.

**Closed as completed by ozum** 2019-12-04 14:02 UTC
